### ISSUE TITLE
[Feature Request] Port to 1.20.x?

### ISSUE THREAD

**Issue by exocyt0sis** [paulevsGitch/BetterWeather#3]
Hi everyone.

Seeing the screenshots portraying BetterWeather almost knocked me off my chair. Local weather with vanilla-style aesthetics is what Mojang should have outfitted Minecraft with in the first place, and seeing what you guys have pulled off so far is _extremely_ encouraging.  I especially enjoy seeing those big clusters of clouds, while the sun peeks forward between them. It looks very dynamic and life-like.

This being said, is there any chance at all for you to please consider porting BetterWeather to 1.20.x, exposing an even wider audience to your mod? From what I've seen so far, it deserves an even larger crowd!

**Comment by paulevsGitch** [comment]
This mod was specifically designed for Minecraft Beta, there are no any plans to port it to any other Minecraft version. Mod is under MIT license, so you are allowed to made port on your own
