### ISSUE TITLE
[Suggestion]Porting to Fabric 1.20.1 or newer

### ISSUE THREAD

**Issue by JDogHLM** [paulevsGitch/BetterWeather#5]
Hello, I am extremely interested in your mod for my modpack, but I discovered that the mod was developed for Minecraft 1.7.3. Do you have any plans to make a port of this mod for fabric/forge Minecraft 1.20.x? This is an extremely impeccable weather mod that is missing in modern versions of the game. There is nothing similar at the moment.

**Comment by paulevsGitch** [comment]
Duplicate of #3

**Comment by paulevsGitch** [comment]
> Minecraft 1.7.3

For Minecraft beta 1.7.3, not for Minecraft release 1.7.3
